description: Pin login fields
required: true
content:
  application/x-www-form-urlencoded:
    schema:
      type: object
      properties:
        default_location_id:
          type: integer
          example: 1
        default_today_view:
          type: string
          enum: [patients, procedures, last-visited]
          example: 'patients'